# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/17138/Desktop/Sirius/Programming/Matrix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/17138/Desktop/Sirius/Programming/Matrix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/17138/Desktop/Sirius/Programming/Matrix/CMakeFiles /mnt/c/Users/17138/Desktop/Sirius/Programming/Matrix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/17138/Desktop/Sirius/Programming/Matrix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code

# Build rule for target.
code: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code
.PHONY : code

# fast build rule for target.
code/fast:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/build
.PHONY : code/fast

AdvanceTest.o: AdvanceTest.cpp.o

.PHONY : AdvanceTest.o

# target to build an object file
AdvanceTest.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/AdvanceTest.cpp.o
.PHONY : AdvanceTest.cpp.o

AdvanceTest.i: AdvanceTest.cpp.i

.PHONY : AdvanceTest.i

# target to preprocess a source file
AdvanceTest.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/AdvanceTest.cpp.i
.PHONY : AdvanceTest.cpp.i

AdvanceTest.s: AdvanceTest.cpp.s

.PHONY : AdvanceTest.s

# target to generate assembly for a file
AdvanceTest.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/AdvanceTest.cpp.s
.PHONY : AdvanceTest.cpp.s

BasicTest.o: BasicTest.cpp.o

.PHONY : BasicTest.o

# target to build an object file
BasicTest.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/BasicTest.cpp.o
.PHONY : BasicTest.cpp.o

BasicTest.i: BasicTest.cpp.i

.PHONY : BasicTest.i

# target to preprocess a source file
BasicTest.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/BasicTest.cpp.i
.PHONY : BasicTest.cpp.i

BasicTest.s: BasicTest.cpp.s

.PHONY : BasicTest.s

# target to generate assembly for a file
BasicTest.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/BasicTest.cpp.s
.PHONY : BasicTest.cpp.s

testmain.o: testmain.cpp.o

.PHONY : testmain.o

# target to build an object file
testmain.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/testmain.cpp.o
.PHONY : testmain.cpp.o

testmain.i: testmain.cpp.i

.PHONY : testmain.i

# target to preprocess a source file
testmain.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/testmain.cpp.i
.PHONY : testmain.cpp.i

testmain.s: testmain.cpp.s

.PHONY : testmain.s

# target to generate assembly for a file
testmain.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/testmain.cpp.s
.PHONY : testmain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... code"
	@echo "... AdvanceTest.o"
	@echo "... AdvanceTest.i"
	@echo "... AdvanceTest.s"
	@echo "... BasicTest.o"
	@echo "... BasicTest.i"
	@echo "... BasicTest.s"
	@echo "... testmain.o"
	@echo "... testmain.i"
	@echo "... testmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

